/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsumerRouteImport } from './routes/consumer'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MetersRouteImport } from './routes/meters'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as RechargesRouteImport } from './routes/recharges'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as TariffsRouteImport } from './routes/tariffs'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MetersRoute = MetersRouteImport.update({
  id: '/meters',
  path: '/meters',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargesRoute = RechargesRouteImport.update({
  id: '/recharges',
  path: '/recharges',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const TariffsRoute = TariffsRouteImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consumer': typeof ConsumerRoute
  '/customers': typeof CustomersRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/meters': typeof MetersRoute
  '/monitoring': typeof MonitoringRoute
  '/recharges': typeof RechargesRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/tariffs': typeof TariffsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consumer': typeof ConsumerRoute
  '/customers': typeof CustomersRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/meters': typeof MetersRoute
  '/monitoring': typeof MonitoringRoute
  '/recharges': typeof RechargesRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/tariffs': typeof TariffsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consumer': typeof ConsumerRoute
  '/customers': typeof CustomersRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/meters': typeof MetersRoute
  '/monitoring': typeof MonitoringRoute
  '/recharges': typeof RechargesRoute
  '/reports': typeof ReportsRoute
  '/simulator': typeof SimulatorRoute
  '/tariffs': typeof TariffsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consumer'
    | '/customers'
    | '/locations'
    | '/login'
    | '/logs'
    | '/meters'
    | '/monitoring'
    | '/recharges'
    | '/reports'
    | '/simulator'
    | '/tariffs'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consumer'
    | '/customers'
    | '/locations'
    | '/login'
    | '/logs'
    | '/meters'
    | '/monitoring'
    | '/recharges'
    | '/reports'
    | '/simulator'
    | '/tariffs'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/consumer'
    | '/customers'
    | '/locations'
    | '/login'
    | '/logs'
    | '/meters'
    | '/monitoring'
    | '/recharges'
    | '/reports'
    | '/simulator'
    | '/tariffs'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsumerRoute: typeof ConsumerRoute
  CustomersRoute: typeof CustomersRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MetersRoute: typeof MetersRoute
  MonitoringRoute: typeof MonitoringRoute
  RechargesRoute: typeof RechargesRoute
  ReportsRoute: typeof ReportsRoute
  SimulatorRoute: typeof SimulatorRoute
  TariffsRoute: typeof TariffsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer': {
      id: '/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meters': {
      id: '/meters'
      path: '/meters'
      fullPath: '/meters'
      preLoaderRoute: typeof MetersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharges': {
      id: '/recharges'
      path: '/recharges'
      fullPath: '/recharges'
      preLoaderRoute: typeof RechargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tariffs': {
      id: '/tariffs'
      path: '/tariffs'
      fullPath: '/tariffs'
      preLoaderRoute: typeof TariffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsumerRoute: ConsumerRoute,
  CustomersRoute: CustomersRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MetersRoute: MetersRoute,
  MonitoringRoute: MonitoringRoute,
  RechargesRoute: RechargesRoute,
  ReportsRoute: ReportsRoute,
  SimulatorRoute: SimulatorRoute,
  TariffsRoute: TariffsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
